### ISSUE TITLE
array has no method 'remove'

### ISSUE THREAD

**Issue by timbowhite** [danielgindi/node-memory-lock#1]
Hey thanks for the module. I got this error when the I couldn't acquire a lock:

```
TypeError: Object [object Object],[object Object] has no method 'remove'
        at null._onTimeout (/var/www/tld-list-dev.com/node_modules/memory-lock/index.js:134:46)
        at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
        throw err;
```

**Comment by timbowhite** [comment]
I think #2 should fix it.

**Comment by danielgindi** [comment]
Oh my!
`remove` was available in my testing environment because of extensions...

**Comment by danielgindi** [comment]
I've pulled and published. Thanks for your contribution! :-)
